Version 2 de las pruebas unitarias para la clase CuatroEnLinea
Pruebas que fallan actualmente:

verificarQueNoPermitaAccederCasilleroDeColumnaMayorAlLimite(juego.CuatroEnLineaTest)
java.lang.Exception: Unexpected exception, expected<java.lang.Error> but was<java.lang.ArrayIndexOutOfBoundsException>
Caused by: java.lang.ArrayIndexOutOfBoundsException: 11
	at juego.CuatroEnLinea.obtenerCasillero(CuatroEnLinea.java:104)

verificarQueNoPermitaAccederCasilleroDeColumnaMenorAUno(juego.CuatroEnLineaTest)
java.lang.Exception: Unexpected exception, expected<java.lang.Error> but was<java.lang.ArrayIndexOutOfBoundsException>
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at juego.CuatroEnLinea.obtenerCasillero(CuatroEnLinea.java:104)

verificarQueNoPermitaAccederCasilleroDeLineaMayorAlLimite(juego.CuatroEnLineaTest)
java.lang.Exception: Unexpected exception, expected<java.lang.Error> but was<java.lang.ArrayIndexOutOfBoundsException>
Caused by: java.lang.ArrayIndexOutOfBoundsException: 5
	at juego.CuatroEnLinea.obtenerCasillero(CuatroEnLinea.java:104)

verificarQueNoPermitaAccederCasilleroDeLineaMenorAUno(juego.CuatroEnLineaTest)
java.lang.Exception: Unexpected exception, expected<java.lang.Error> but was<java.lang.ArrayIndexOutOfBoundsException>
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at juego.CuatroEnLinea.obtenerCasillero(CuatroEnLinea.java:104)